import React, { useState } from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import ContentWrapper from '@components/common/ContentWrapper';
import Modal from '@mui/material/Modal';
import TradingBotAdd from '@containers/TradingBot/TradingAddContainer';

const TradingBot = (): JSX.Element => {
  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <>
      <ContentWrapper
        title="TradingBot"
        addButton={<>add</>}
        handleOpen={handleOpen}
      >
        <div>
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
          &nbsp;TradingBot TradingBot Content &nbsp; TradingBot Content &nbsp;
        </div>
      </ContentWrapper>
      <Modal open={open} onClose={handleClose}>
        <TradingBotAdd handleClose={handleClose} />
      </Modal>
    </>
  );
};
export default TradingBot;
